from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author. Must be 'user' or 'assistant'.")
    content: str = Field(..., description="The textual body content of the message.")

class ChatRequest(BaseModel):
    message: str = Field(..., description="The fresh incoming natural language prompt from the user.")
    history: List[ChatMessage] = Field(
        default=[], 
        description="The active conversation history to maintain context awareness across interactions."
    )

class Citation(BaseModel):
    source: str = Field(..., description="The identifier or file name of the document context used.")
    text: str = Field(..., description="The exact raw text snippet retrieved from the vector storage layer.")
    score: float = Field(..., description="The similarity/confidence score of the semantic search hit.")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="The fully synthesized response generated by the grounded LLM.")
    citations: List[Citation] = Field(
        default=[], 
        description="The collection of source records confirming the validity of the answer."
    )